# Generated by Django 4.1.7 on 2023-03-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choice_1',
            field=models.BooleanField(default=False, verbose_name='Choice 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='choice_2',
            field=models.BooleanField(default=False, verbose_name='Choice 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='choice_3',
            field=models.BooleanField(default=False, verbose_name='Choice 3'),
        ),
    ]
