# Generated by Django 4.1.7 on 2023-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_choice_1_profile_choice_2_profile_choice_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choice_1',
            field=models.BooleanField(default=False, verbose_name='Nitflex'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='choice_2',
            field=models.BooleanField(default=False, verbose_name='HPO'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='choice_3',
            field=models.BooleanField(default=False, verbose_name='Disnep+'),
        ),
    ]
