# Generated by Django 4.1.7 on 2023-03-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_choice_1_alter_profile_choice_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choice_3',
            field=models.BooleanField(default=False, verbose_name='Disnep'),
        ),
    ]
