# Generated by Django 4.1.7 on 2023-03-04 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=128, verbose_name='email address')),
                ('password', models.CharField(db_index=True, max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=128, verbose_name='phone number')),
            ],
            options={
                'ordering': ['email', 'password', 'first_name', 'last_name', 'phone_number'],
            },
        ),
    ]
