# Generated by Django 4.1.7 on 2023-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_f_name', models.CharField(db_index=True, max_length=50, verbose_name='first name')),
                ('actor_l_name', models.CharField(db_index=True, max_length=50, verbose_name='last name')),
            ],
            options={
                'ordering': ['actor_f_name', 'actor_l_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(db_index=True, max_length=50, verbose_name='genre')),
            ],
            options={
                'ordering': ['genre_name'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_f_name', models.CharField(db_index=True, max_length=50, verbose_name='first name')),
                ('producer_l_name', models.CharField(db_index=True, max_length=50, verbose_name='last name')),
            ],
            options={
                'ordering': ['producer_f_name', 'producer_l_name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(db_index=True, max_length=100, verbose_name='movie name')),
                ('description', models.TextField(verbose_name='description')),
                ('release_date', models.DateTimeField(verbose_name='publish date')),
                ('actors', models.ManyToManyField(to='flexzone.actor', verbose_name='actors')),
                ('genres', models.ManyToManyField(to='flexzone.genre', verbose_name='Genres')),
                ('producers', models.ManyToManyField(to='flexzone.producer', verbose_name='producer')),
            ],
        ),
    ]
