# Generated by Django 4.1.7 on 2023-03-04 20:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0003_alter_movie_options_alter_movie_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pack', models.CharField(max_length=100, verbose_name='subscription pack')),
            ],
            options={
                'ordering': ['pack'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email', 'password', 'first_name', 'last_name', 'phone_number', 'subscription']},
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexzone.subscriptionpack', verbose_name='subscription'),
        ),
    ]
