# Generated by Django 4.1.7 on 2023-03-04 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0004_subscriptionpack_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email', 'password', 'first_name', 'last_name', 'phone_number', 'subscription__pack']},
        ),
        migrations.AlterField(
            model_name='subscriptionpack',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(to='flexzone.subscriptionpack', verbose_name='subscription'),
        ),
    ]
