# Generated by Django 4.1.7 on 2023-03-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0005_alter_user_options_alter_subscriptionpack_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subscription_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexzone.subscriptionpack', verbose_name=''),
        ),
    ]
