# Generated by Django 4.1.7 on 2023-03-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0006_movie_subscription_pack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['movie_name', 'description', 'subscription_pack', 'genres__genre_name', 'producers__producer_f_name', 'producers__producer_l_name', 'release_date', 'actors__actor_f_name', 'actors__actor_l_name']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='subscription_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexzone.subscriptionpack', verbose_name='subscription package'),
        ),
        migrations.CreateModel(
            name='TvSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(db_index=True, max_length=100, verbose_name='show name')),
                ('description', models.TextField(verbose_name='description')),
                ('season', models.IntegerField(verbose_name='season')),
                ('episode', models.IntegerField(verbose_name='episode')),
                ('release_date', models.DateField(verbose_name='publish date')),
                ('actors', models.ManyToManyField(to='flexzone.actor', verbose_name='actors')),
                ('genres', models.ManyToManyField(to='flexzone.genre', verbose_name='Genres')),
                ('producers', models.ManyToManyField(to='flexzone.producer', verbose_name='producer')),
                ('subscription_pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexzone.subscriptionpack', verbose_name='subscription package')),
            ],
            options={
                'ordering': ['show_name', 'description', 'subscription_pack', 'season', 'episode', 'genres__genre_name', 'producers__producer_f_name', 'producers__producer_l_name', 'release_date', 'actors__actor_f_name', 'actors__actor_l_name'],
            },
        ),
    ]
