# Generated by Django 4.1.7 on 2023-03-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0007_alter_movie_options_alter_movie_subscription_pack_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TvSeries',
            new_name='TvShow',
        ),
        migrations.AlterField(
            model_name='movie',
            name='subscription_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flexzone.subscriptionpack', verbose_name='subscription package'),
        ),
    ]
