# Generated by Django 4.1.7 on 2023-03-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0008_rename_tvseries_tvshow_alter_movie_subscription_pack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title', 'description', 'subscription_pack', 'genres__genre_name', 'producers__producer_f_name', 'producers__producer_l_name', 'release_date', 'actors__actor_f_name', 'actors__actor_l_name']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='subscription_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='flexzone.subscriptionpack', verbose_name='subscription package'),
        ),
    ]
