# Generated by Django 4.1.7 on 2023-03-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0010_alter_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('n', 'Nitflex'), ('h', 'HPO'), ('d', 'Disnep+')], default='n', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flexzone/thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='subscription_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='flexzone.subscriptionpack', verbose_name='subscription level'),
        ),
    ]
