# Generated by Django 4.1.7 on 2023-03-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0012_alter_movie_options_alter_tvshow_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='status',
            new_name='group',
        ),
    ]
