# Generated by Django 4.1.7 on 2023-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0013_rename_status_movie_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='group',
            field=models.CharField(choices=[('-', '---------'), ('n', 'Nitflex'), ('h', 'HPO'), ('d', 'Disnep')], default='-', max_length=1, verbose_name='group'),
        ),
    ]
