# Generated by Django 4.1.7 on 2023-03-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0015_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='flexzone.genre', verbose_name='Genres'),
        ),
    ]
