# Generated by Django 4.1.7 on 2023-03-28 23:59

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flexzone', '0018_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True, verbose_name='video url'),
        ),
    ]
